### PR TITLE
Pin runtime requirements on minor versions

### PR DESCRIPTION
**Pull request by jjerphan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jjerphan** [comment]
@conda-forge-admin, please rerender

**Review by xhochy — APPROVED** [review]

**Comment by xhochy** [comment]
Will merge once we have the repodata patch in place and adjusted conda-forge-pinning.

**Comment by pentschev** [comment]
Thanks for working on this. I was just about to file an issue in https://github.com/conda-forge/orc-feedstock as I've observed the snappy upgrade has broken https://github.com/conda-forge/arrow-feedstock :

```python
$ python -c "import pyarrow"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/arrow/lib/python3.9/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
ImportError: /opt/conda/envs/arrow/lib/python3.9/site-packages/pyarrow/../../.././liborc.so: undefined symbol: _ZN6snappy11RawCompressEPKcmPcPm=
```

I'm not familiar with all behavior this pin will have, will it prevent `orc` from installing `snappy>=1.2`, or would other changes be required? Perhaps listing [`snappy` in conda-forge-pinning-feedstock’s arch_rebuild](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/arch_rebuild.txt) would be needed?

**Comment by jjerphan** [comment]
> I'm not familiar with all behavior this pin will have, will it prevent orc from installing snappy>=1.2, or would other changes be required? Perhaps listing [snappy in conda-forge-pinning-feedstock’s arch_rebuild](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/arch_rebuild.txt) would be needed?

https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/699 addresses it.

**Comment by jjerphan** [comment]
Must we introduce stricter tests for `osx` and `linux` builds' shared objects SONAMEs?

**Comment by xhochy** [comment]
🤞

**Pull request merged**
