### PR TITLE
Snappy must be compiled with -fPIC for static linking

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Comment by wesm** [comment]
@groutr @jakirkham I need this for other builds that I'm working on, so merge away if it won't cause any obvious problems

**Comment by jakirkham** [comment]
What can I say it's hard to keep track of things here? 😄

We actually have this already ( https://github.com/conda-forge/snappy-feedstock ). If there are changes that you think are worthwhile @wesm, please submit a PR.

**Comment by wesm** [comment]
Just to confirm, these are changes to an existing feedstock and will unblock any recipe requiring static linking to snappy. Note that zlib compiles it static libs with `-fPIC` without extra configuration so there are 
not static linking problems. the error looks like:

```
/usr/bin/ld: /home/wesm/anaconda3/envs/_build/lib/libsnappy.a(snappy.o): 
relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
```

**Comment by wesm** [comment]
Actually, I'm not sure about that, I'm having static linker issues with the conda-forge libz now too, I may submit a patch there shortly

**Comment by wesm** [comment]
OK, I'm in business now with these zlib and snappy patches. It will be a while until we put parquet-cpp into conda-forge as we have not yet made an official release yet.

**Comment by wesm** [comment]
related: conda-forge/zlib-feedstock#4 . Can we merge this in?

**Comment by wesm** [comment]
Is this good to go?

**Comment by jakirkham** [comment]
LGTM. Thanks @wesm. Sorry for the wait.

**Comment by wesm** [comment]
thank you

**Pull request merged**
